export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8081/api';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
  },
  CUSTOMERS: {
    LIST: '/customers',
    CREATE: '/customers',
    DETAIL: (id: string) => `/customers/${id}`,
    UPDATE: (id: string) => `/customers/${id}`,
    DELETE: (id: string) => `/customers/${id}`,
    ACTIVATE: (id: string) => `/customers/${id}/activate`,
    DEACTIVATE: (id: string) => `/customers/${id}/deactivate`,
    SUSPEND: (id: string) => `/customers/${id}/suspend`,
    STATS: '/customers/stats',
    EXPORT: '/customers/export',
    BULK_UPDATE_STATUS: '/customers/bulk-update-status',
    SEARCH: '/customers/search',
    ASSIGN_METER: (id: string) => `/customers/${id}/assign-meter`,
  },
  SUBSCRIPTION_TYPES: {
    LIST: '/subscription-types',
    CREATE: '/subscription-types',
    DETAIL: (id: string) => `/subscription-types/${id}`,
    UPDATE: (id: string) => `/subscription-types/${id}`,
    DELETE: (id: string) => `/subscription-types/${id}`,
  },
  INVOICES: {
    LIST: '/invoices',
    CREATE: '/invoices',
    DETAIL: (id: string) => `/invoices/${id}`,
    UPDATE: (id: string) => `/invoices/${id}`,
    DELETE: (id: string) => `/invoices/${id}`,
    GENERATE_BULK: '/invoices/generate-bulk',
    SEND: (id: string) => `/invoices/${id}/send`,
    VOID: (id: string) => `/invoices/${id}/void`,
    PDF: (id: string) => `/invoices/${id}/pdf`,
  },
  PAYMENTS: {
    LIST: '/payments',
    CREATE: '/payments',
    GET: '/payments/:id',
    UPDATE: '/payments/:id',
    DELETE: '/payments/:id',
    BY_INVOICE: '/payments/invoice/:invoiceId',
    OUTSTANDING_INVOICES: '/invoices/outstanding',
    VOID: '/payments/:id/void',
    GENERATE_RECEIPT: '/payments/:id/receipt',
    GET_RECEIPT: '/payments/:id/receipt',
    EXPORT: '/payments/export',
  },
  WATER_USAGE: {
    LIST: '/water-usage',
    CREATE: '/water-usage',
    DETAIL: (id: string) => `/water-usage/${id}`,
    UPDATE: (id: string) => `/water-usage/${id}`,
    DELETE: (id: string) => `/water-usage/${id}`,
    BULK_IMPORT: '/water-usage/bulk-import',
    BY_CUSTOMER: (customerId: string) => `/water-usage/customer/${customerId}`,
  },
  WATER_RATES: {
    LIST: '/water-rates',
    CREATE: '/water-rates',
    DETAIL: (id: string) => `/water-rates/${id}`,
    UPDATE: (id: string) => `/water-rates/${id}`,
    DELETE: (id: string) => `/water-rates/${id}`,
    CURRENT: '/water-rates/current',
  },
  REPORTS: {
    REVENUE: '/reports/revenue',
    CUSTOMERS: '/reports/customers',
    USAGE: '/reports/usage',
    PAYMENTS: '/reports/payments',
    OUTSTANDING: '/reports/outstanding',
    EXPORT: '/reports/export',
  },
};